[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_PINATA_JWT"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 让百度验证文件不被强制重定向到 HTTPS
[[redirects]]
  from = "/baidu_verify_codeva-8b7e3341070b661db4e92c0711ff2212.html"
  to = "/baidu_verify_codeva-8b7e3341070b661db4e92c0711ff2212.html"
  status = 200
  force = true